services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: l0c4lD3v3l0pm3nt
  be:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=l0c4lD3v3l0pm3nt
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "3000:80"
    command: >
      sh -c "npm run docker:migration && npm run start"
